# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/project_fz/project_fz.srcs/sources_1/ip/fontRom/fontRom.xci
# IP: The module: 'fontRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project_fz/project_fz.srcs/sources_1/ip/fontRom/fontRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fontRom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/project_fz/project_fz.srcs/sources_1/ip/fontRom/fontRom.xci
# IP: The module: 'fontRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project_fz/project_fz.srcs/sources_1/ip/fontRom/fontRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fontRom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
