# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/GitHub/TestVGA/Computer/Computer.srcs/sources_1/ip/fifo_mem/fifo_mem.xci
# IP: The module: 'fifo_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub/TestVGA/Computer/Computer.srcs/sources_1/ip/fifo_mem/fifo_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/GitHub/TestVGA/Computer/Computer.srcs/sources_1/ip/fifo_mem/fifo_mem.xci
# IP: The module: 'fifo_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub/TestVGA/Computer/Computer.srcs/sources_1/ip/fifo_mem/fifo_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
