# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tlfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/project_fz/project_fz.cache/wt [current_project]
set_property parent.project_path E:/project_fz/project_fz.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo e:/project_fz/project_fz.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/ALU.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/AMux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/BMux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/Controller.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/ExMemRegisters.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/ForwardController.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/HazardDetectionUnit.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/IdExRegisters.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/IfIdRegisters.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/ImmeExtendUnit.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/MFPCMux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/MemWbRegisters.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/MemoryUnit.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/PCAdder.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/PCMux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/PCRegister.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/RdMux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/ReadReg1Mux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/ReadReg2Mux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/Registers.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/StructConflictUnit.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/VGA_Controller.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/WriteDataMux.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/clock.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/dcm.vhd
  E:/project_fz/project_fz.srcs/sources_1/imports/cpu_fz/cpu.vhd
}
read_ip -quiet e:/project_fz/project_fz.srcs/sources_1/ip/fontRom/fontRom.xci
set_property used_in_implementation false [get_files -all e:/project_fz/project_fz.srcs/sources_1/ip/fontRom/fontRom_ooc.xdc]
set_property is_locked true [get_files e:/project_fz/project_fz.srcs/sources_1/ip/fontRom/fontRom.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/project_fz/project_fz.srcs/constrs_1/new/cpu.xdc
set_property used_in_implementation false [get_files E:/project_fz/project_fz.srcs/constrs_1/new/cpu.xdc]


synth_design -top cpu -part xc7a100tlfgg676-2L


write_checkpoint -force -noxdef cpu.dcp

catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
